# Generated by Django 5.2.3 on 2025-07-06 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Googlelogin', '0008_save_post_by_user_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=100)),
                ('plan_description', models.CharField(max_length=200)),
                ('post', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='save_post_by_user',
            name='job_id',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='FinalSubscriptionForEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('receipent_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Googlelogin.plan1')),
            ],
        ),
    ]
