# Generated by Django 5.2.3 on 2025-07-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Googlelogin', '0009_plan1_alter_save_post_by_user_job_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='finalsubscriptionforemployee',
            table='Final_subscrtion_for_employee',
        ),
        migrations.AlterModelTable(
            name='plan1',
            table='Plan1',
        ),
    ]
