# Generated by Django 5.2.3 on 2025-07-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Googlelogin', '0010_alter_finalsubscriptionforemployee_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan1',
            old_name='plan_description',
            new_name='plain_discreption',
        ),
    ]
