# Generated by Django 5.2.3 on 2025-07-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Googlelogin', '0011_rename_plan_description_plan1_plain_discreption'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='employee_id',
            field=models.CharField(default='', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
